[package]
name = "libsbscraper"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "rustls-tls"] }
rss = "2.0.11"
scraper = "0.21.0"
